apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pablombatalla/argo.git
    targetRevision: HEAD
    path: argo/example1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example1
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
